apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd-self
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/sefire-org/gitops
    targetRevision: HEAD
    path: apps/argo-cd
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
